-- ============================================================
-- ESQUEMA BASE (v1) — placeholder
-- ============================================================
-- El esquema inicial (tablas roles, empleados, categorias, productos,
-- inventario, toppings, metodos_pago, facturas, productos_facturas,
-- facturas_pagos, aperturas_caja, auditoria) se creó a mano en el editor SQL
-- de Supabase antes de adoptar migraciones, así que no existe como migración.
--
-- El esquema COMPLETO y al día (base v1 + v2..v10) está en:
--   supabase/schema.sql
--
-- Para levantar una instancia nueva NO se aplican estas migraciones una por
-- una: se ejecuta supabase/schema.sql + supabase/seed.sql. Ver PROVISIONING.md.
--
-- Las migraciones v2..v10 de esta carpeta son solo el historial del proyecto
-- original y asumen que las tablas base ya existen.
